schema: 1

type: "poet"
title: "عطار نیشابوری"

description: >
  فریدالدین ابوحامد محمد عطار نیشابوری (متوفی حدود 618 ه.ق.) از بزرگترین
  شاعران و عارفان ایران است.

tags:
  - "قرن-ششم"
  - "مثنوی"
  - "عرفان"

children:
  - منطق-الطیر
